import { config } from "./config";

export const VideoData = [ 
    {
        title:'Image Slider Using HTML, CSS, and JavaScript',
        thumbnail: config.THUMBNAIL1,
        channelName:'Coding Power',
        channelLogo: config.ACCOUNT_LOGO,
        videoLength: '7:08',
        views: '28 Views',
        uploadTime:'3 week ago',
    },
    {
        title:'Netflix Home Page Using HTML and CSS',
        thumbnail: config.THUMBNAIL2,
        channelName:'Coding Power',
        channelLogo: config.ACCOUNT_LOGO,
        videoLength: '12:40',
        views: '160 Views',
        uploadTime:'3 week ago',
    },
    {
        title:'How To Create Login Form In HTML and CSS',
        thumbnail: config.THUMBNAIL3,
        channelName:'Coding Power',
        channelLogo: config.ACCOUNT_LOGO,
        videoLength: '8:20',
        views: '33 Views',
        uploadTime:'1 week ago',
    },
    {
        title:'Drop Down Menu using HTML and CSS',
        thumbnail: config.THUMBNAIL4,
        channelName:'Coding Power',
        channelLogo: config.ACCOUNT_LOGO,
        videoLength: '5:40',
        views: '25 Views',
        uploadTime:'2 week ago',
    },
    {
        title:'Full Screen Video Background Using HTML',
        thumbnail: config.THUMBNAIL5,
        channelName:'Coding Power',
        channelLogo: config.ACCOUNT_LOGO,
        videoLength: '9:30',
        views: '10 Views',
        uploadTime:'2 week ago',
    },
    {
        title:'Pricing Table Using HTML & CSS',
        thumbnail: config.THUMBNAIL6,
        channelName:'Coding Power',
        channelLogo: config.ACCOUNT_LOGO,
        videoLength: '10:20',
        views: '15 Views',
        uploadTime:'3 week ago',
    },
    {
        title:'How to Make Video Gallery Using HTML, CSS',
        thumbnail: config.THUMBNAIL7,
        channelName:'Coding Power',
        channelLogo: config.ACCOUNT_LOGO,
        videoLength: '8:08',
        views: '36 Views',
        uploadTime:'3 week ago',
    },
    {
        title:'Responsive Gallery Using HTML and CSS',
        thumbnail: config.THUMBNAIL8,
        channelName:'Coding Power',
        channelLogo: config.ACCOUNT_LOGO,
        videoLength: '6:50',
        views: '22 Views',
        uploadTime:'1 week ago',
    },
]